[package]
name = "bodo"
version = "0.1.0"
edition = "2021"
description = "A modern task runner and build tool"
license = "MIT"
repository = "https://github.com/bodo-run/bodo"

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
serde_yaml = "0.9.30"
serde_json = "1.0.111"
tokio = { version = "1.35.1", features = ["full"] }
colored = "2.1.0"
notify = "6.1.1"
walkdir = "2.5"
glob = "0.3.1"
toml = "0.8"
thiserror = "1.0"
anyhow = "1.0"
async-trait = "0.1.77"
futures = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4.4.18", features = ["derive"] }
humantime = "2.1.0"
chrono = "0.4.31"
rayon = "1.7"
dialoguer = "0.11"
petgraph = "0.6"
libc = "0.2.151"
nix = "0.27.1"
ctrlc = "3.4.1"
yaml-rust = "0.4.5"

[dev-dependencies]
tempfile = "3.9.0"
tokio-test = "0.4"
assert_cmd = "2.0"
predicates = "3.0"
