[package]
name = "bodo"
version = "0.1.0"
edition = "2021"
authors = ["Mohsen"]
description = "Task runner in Rust"

[lib]
path = "src/lib.rs"

[[bin]]
name = "bodo"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
rayon = "1.7"
notify = "6.1"
dialoguer = "0.11"
petgraph = "0.6"
clap = { version = "4.4.11", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
colored = "2.1.0"

[dev-dependencies]
assert_cmd = "2.0"
predicates = { version = "3.0", features = ["regex"] }
tempfile = "3.8"
