output_dir = "./repo-serialized"

# Add patterns to ignore (in addition to .gitignore)
ignore_patterns = [
    "docs/",
    "target/",
    "Cargo.lock",
    "LICENSE",
    "README.md",
    "CONTRIBUTING.md",
    "CODE_OF_CONDUCT.md",
    "CHANGELOG.md",
    ".cargo/",
    ".rustup/",
    "examples/",
    "repo-serialized/",
    ".vscode/",
    ".github/",
    ".gitignore",
    ".cursorrules",
    "scripts/",
]

# Define priority rules for processing order
# Higher scores are processed first
[[priority_rules]]
score = 100
pattern = "^src/"

[[priority_rules]]
score = 90
pattern = "^src/plugins/"

[[priority_rules]]
score = 40
pattern = "^tests/"

# Add additional binary file extensions to ignore
binary_extensions = [
    ".rlib",   # Rust static libraries
    ".rmeta",  # Rust metadata files
    ".dll",    # Dynamic libraries
    ".so",     # Shared objects
    ".dylib"   # Dynamic libraries (macOS)
] 