use crate::graph::Graph;
use crate::Result;
use crate::errors::RecoveryStrategy;
use crate::recovery::{RecoveryExecutor, RetryConfig};
use std::any::Any;
use std::collections::HashMap;
use std::path::PathBuf;
use std::time::Duration;

/// Represents a side effect that would occur during execution
#[derive(Debug, Clone)]
pub enum SideEffect {
    /// Writing to a file
    FileWrite(PathBuf),
    /// Reading from a file
    FileRead(PathBuf),
    /// Making a network request
    NetworkRequest(String),
    /// Spawning a process
    ProcessSpawn(String),
    /// Changing an environment variable
    EnvironmentChange(String, String),
}

/// Report generated by dry-run execution containing details about what would be executed
#[derive(Debug, Clone)]
pub struct DryRunReport {
    /// The command that would be executed
    pub command: String,
    /// Environment variables that would be set
    pub environment: HashMap<String, String>,
    /// Working directory for the command
    pub working_directory: PathBuf,
    /// List of dependencies that would be resolved
    pub dependencies: Vec<String>,
    /// Estimated time the command would take to run
    pub estimated_duration: Option<Duration>,
    /// List of potential side effects from execution
    pub side_effects: Vec<SideEffect>,
}

/// Execution context for dry-run operations
#[derive(Debug, Clone)]
pub struct ExecutionContext {
    /// Working directory for execution
    pub working_directory: PathBuf,
    /// Environment variables
    pub environment: HashMap<String, String>,
    /// Whether we are in dry-run mode
    pub dry_run: bool,
}

/// Trait for plugins that support dry-run mode
///
/// Plugins implementing this trait can simulate their execution without
/// performing actual side effects, useful for previewing what would happen.
pub trait DryRunnable {
    /// Simulate execution and return a report of what would happen
    fn dry_run(&self, context: &ExecutionContext) -> Result<DryRunReport>;
}

/// Trait for plugins that support error recovery strategies
///
/// Plugins implementing this trait can define custom recovery behaviors
/// for different types of errors and operations.
pub trait Recoverable {
    /// Get the recovery strategy for this plugin
    fn recovery_strategy(&self) -> RecoveryStrategy {
        // Default strategy: retry up to 3 times with 100ms initial backoff
        RecoveryStrategy::Retry {
            max_attempts: 3,
            backoff: Duration::from_millis(100),
        }
    }

    /// Handle recovery for a specific error
    /// Returns true if recovery was successful and operation should be retried
    fn handle_recovery(&mut self, error: &crate::errors::BodoError) -> Result<bool> {
        // Default implementation: let the recovery executor handle it
        Ok(error.is_retryable())
    }

    /// Create a checkpoint before executing a critical operation
    fn create_checkpoint(&self, _context: &ExecutionContext) -> Result<Option<crate::errors::TaskCheckpoint>> {
        // Default implementation: no checkpointing
        Ok(None)
    }
}

/// Synchronous plugin trait (no `async` anymore).
pub trait Plugin: Send {
    fn name(&self) -> &'static str;
    fn priority(&self) -> i32;
    fn as_any(&self) -> &dyn Any;

    /// Called after plugin is created, before building the graph.
    fn on_init(&mut self, _config: &PluginConfig) -> Result<()> {
        Ok(())
    }

    /// Called when building/modifying the graph (e.g. adding concurrency).
    fn on_graph_build(&mut self, _graph: &mut Graph) -> Result<()> {
        Ok(())
    }

    /// Called after the graph is built but before final execution.
    fn on_after_run(&mut self, _graph: &mut Graph) -> Result<()> {
        Ok(())
    }

    /// Called each time we run an individual node (not used here by default).
    fn on_run(&mut self, _node_id: usize, _graph: &mut Graph) -> Result<()> {
        Ok(())
    }
}

/// Configuration passed to plugins during initialization
#[derive(Default)]
pub struct PluginConfig {
    /// Whether to stop execution on first failure
    pub fail_fast: bool,
    /// Whether to enable watch mode
    pub watch: bool,
    /// Whether to only list available tasks
    pub list: bool,
    /// Whether to run in dry-run mode (simulation without side effects)
    pub dry_run: bool,
    /// Enable error recovery mechanisms
    pub enable_recovery: bool,
    /// Maximum retry attempts for all operations
    pub max_retry_attempts: Option<u32>,
    /// Initial backoff duration for retries
    pub initial_retry_backoff: Option<Duration>,
    /// Additional plugin-specific options
    pub options: Option<serde_json::Map<String, serde_json::Value>>,
}

pub struct PluginManager {
    plugins: Vec<Box<dyn Plugin>>,
    recovery_executor: RecoveryExecutor,
}

impl PluginManager {
    pub fn new() -> Self {
        Self {
            plugins: Vec::new(),
            recovery_executor: RecoveryExecutor::default(),
        }
    }

    pub fn sort_plugins(&mut self) {
        self.plugins
            .sort_by_key(|p| std::cmp::Reverse(p.priority()));
    }

    pub fn register(&mut self, plugin: Box<dyn Plugin>) {
        self.plugins.push(plugin);
    }

    /// Provide read-only access to the plugins, for testing purposes
    pub fn get_plugins(&self) -> &[Box<dyn Plugin>] {
        &self.plugins
    }

    /// Runs the "lifecycle" in a blocking (synchronous) manner with recovery support.
    pub fn run_lifecycle(&mut self, graph: &mut Graph, config: Option<PluginConfig>) -> Result<()> {
        let config = config.unwrap_or_default();
        self.sort_plugins();

        // Configure recovery executor if recovery is enabled
        if config.enable_recovery {
            let retry_config = RetryConfig {
                max_attempts: config.max_retry_attempts.unwrap_or(3),
                initial_backoff: config.initial_retry_backoff.unwrap_or(Duration::from_millis(100)),
                ..Default::default()
            };
            self.recovery_executor = RecoveryExecutor::new(retry_config);
            tracing::info!("Recovery mechanisms enabled for plugin lifecycle");
        }

        // on_init with recovery
        for plugin in &mut self.plugins {
            if config.enable_recovery {
                let plugin_name = plugin.name();
                self.recovery_executor.execute_strategy(
                    &RecoveryStrategy::Retry {
                        max_attempts: config.max_retry_attempts.unwrap_or(3),
                        backoff: config.initial_retry_backoff.unwrap_or(Duration::from_millis(100)),
                    },
                    || {
                        tracing::debug!(plugin = plugin_name, "Running on_init with recovery");
                        plugin.on_init(&config)
                    },
                )?;
            } else {
                plugin.on_init(&config)?;
            }
        }

        // on_graph_build with recovery
        for plugin in &mut self.plugins {
            if config.enable_recovery {
                let plugin_name = plugin.name();
                self.recovery_executor.execute_strategy(
                    &RecoveryStrategy::Retry {
                        max_attempts: config.max_retry_attempts.unwrap_or(3),
                        backoff: config.initial_retry_backoff.unwrap_or(Duration::from_millis(100)),
                    },
                    || {
                        tracing::debug!(plugin = plugin_name, "Running on_graph_build with recovery");
                        plugin.on_graph_build(graph)
                    },
                )?;
            } else {
                plugin.on_graph_build(graph)?;
            }
        }

        // on_after_run with recovery
        for plugin in &mut self.plugins {
            if config.enable_recovery {
                let plugin_name = plugin.name();
                self.recovery_executor.execute_strategy(
                    &RecoveryStrategy::Retry {
                        max_attempts: config.max_retry_attempts.unwrap_or(3),
                        backoff: config.initial_retry_backoff.unwrap_or(Duration::from_millis(100)),
                    },
                    || {
                        tracing::debug!(plugin = plugin_name, "Running on_after_run with recovery");
                        plugin.on_after_run(graph)
                    },
                )?;
            } else {
                plugin.on_after_run(graph)?;
            }
        }

        // Log metrics summary if recovery was used
        if config.enable_recovery {
            let summary = crate::metrics::get_metrics_summary();
            tracing::info!(metrics_summary = %summary, "Plugin lifecycle completed with recovery");
        }

        Ok(())
    }
}

impl Default for PluginManager {
    fn default() -> Self {
        Self::new()
    }
}
