use crate::graph::Graph;
use crate::Result;
use std::any::Any;
use std::collections::HashMap;
use std::path::PathBuf;
use std::time::Duration;

/// Represents a side effect that would occur during execution
#[derive(Debug, Clone)]
pub enum SideEffect {
    /// Writing to a file
    FileWrite(PathBuf),
    /// Reading from a file
    FileRead(PathBuf),
    /// Making a network request
    NetworkRequest(String),
    /// Spawning a process
    ProcessSpawn(String),
    /// Changing an environment variable
    EnvironmentChange(String, String),
}

/// Report generated by dry-run execution containing details about what would be executed
#[derive(Debug, Clone)]
pub struct DryRunReport {
    /// The command that would be executed
    pub command: String,
    /// Environment variables that would be set
    pub environment: HashMap<String, String>,
    /// Working directory for the command
    pub working_directory: PathBuf,
    /// List of dependencies that would be resolved
    pub dependencies: Vec<String>,
    /// Estimated time the command would take to run
    pub estimated_duration: Option<Duration>,
    /// List of potential side effects from execution
    pub side_effects: Vec<SideEffect>,
}

/// Execution context for dry-run operations
#[derive(Debug, Clone)]
pub struct ExecutionContext {
    /// Working directory for execution
    pub working_directory: PathBuf,
    /// Environment variables
    pub environment: HashMap<String, String>,
    /// Whether we are in dry-run mode
    pub dry_run: bool,
}

/// Trait for plugins that support dry-run mode
/// 
/// Plugins implementing this trait can simulate their execution without 
/// performing actual side effects, useful for previewing what would happen.
pub trait DryRunnable {
    /// Simulate execution and return a report of what would happen
    fn dry_run(&self, context: &ExecutionContext) -> Result<DryRunReport>;
}

/// Synchronous plugin trait (no `async` anymore).
pub trait Plugin: Send {
    fn name(&self) -> &'static str;
    fn priority(&self) -> i32;
    fn as_any(&self) -> &dyn Any;

    /// Called after plugin is created, before building the graph.
    fn on_init(&mut self, _config: &PluginConfig) -> Result<()> {
        Ok(())
    }

    /// Called when building/modifying the graph (e.g. adding concurrency).
    fn on_graph_build(&mut self, _graph: &mut Graph) -> Result<()> {
        Ok(())
    }

    /// Called after the graph is built but before final execution.
    fn on_after_run(&mut self, _graph: &mut Graph) -> Result<()> {
        Ok(())
    }

    /// Called each time we run an individual node (not used here by default).
    fn on_run(&mut self, _node_id: usize, _graph: &mut Graph) -> Result<()> {
        Ok(())
    }
}

/// Configuration passed to plugins during initialization
#[derive(Default)]
pub struct PluginConfig {
    /// Whether to stop execution on first failure
    pub fail_fast: bool,
    /// Whether to enable watch mode
    pub watch: bool,
    /// Whether to only list available tasks
    pub list: bool,
    /// Whether to run in dry-run mode (simulation without side effects)
    pub dry_run: bool,
    /// Additional plugin-specific options
    pub options: Option<serde_json::Map<String, serde_json::Value>>,
}

pub struct PluginManager {
    plugins: Vec<Box<dyn Plugin>>,
}

impl PluginManager {
    pub fn new() -> Self {
        Self {
            plugins: Vec::new(),
        }
    }

    pub fn sort_plugins(&mut self) {
        self.plugins
            .sort_by_key(|p| std::cmp::Reverse(p.priority()));
    }

    pub fn register(&mut self, plugin: Box<dyn Plugin>) {
        self.plugins.push(plugin);
    }

    /// Provide read-only access to the plugins, for testing purposes
    pub fn get_plugins(&self) -> &[Box<dyn Plugin>] {
        &self.plugins
    }

    /// Runs the "lifecycle" in a blocking (synchronous) manner.
    pub fn run_lifecycle(&mut self, graph: &mut Graph, config: Option<PluginConfig>) -> Result<()> {
        let config = config.unwrap_or_default();
        self.sort_plugins();

        // on_init
        for plugin in &mut self.plugins {
            plugin.on_init(&config)?;
        }
        // on_graph_build
        for plugin in &mut self.plugins {
            plugin.on_graph_build(graph)?;
        }
        // on_after_run
        for plugin in &mut self.plugins {
            plugin.on_after_run(graph)?;
        }
        Ok(())
    }
}

impl Default for PluginManager {
    fn default() -> Self {
        Self::new()
    }
}
