name: AI Loop

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run"
        required: true
        default: "main"
      attempts:
        description: "Max attempts"
        default: "40"
        type: number
      pr-on-fail:
        description: "Create a PR on failure"
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  loop:
    name: AI Loop
    runs-on: ubuntu-latest
    timeout-minutes: 360
    env:
      MAX_ATTEMPTS: ${{ github.event.inputs.attempts }}
      CARGO_TERM_COLOR: always
      RUSTFLAGS: "-Cinstrument-coverage"
      LLVM_PROFILE_FILE: "coverage/bodo-%p-%m.profraw"
      BRANCH: ${{ github.event.inputs.branch }}

    steps:
      - name: Print inputs
        run: |
          echo "MAX_ATTEMPTS=${{ env.MAX_ATTEMPTS }}"

      - name: Install Bodo
        run: curl -fsSL https://bodo.run/bodo.sh | bash

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Yek
        run: |
          curl -fsSL https://bodo.run/yek.sh | bash

      - name: Install grcov
        run: cargo install grcov

      - name: Install llvm-cov
        run: cargo +stable install cargo-llvm-cov --locked

      - name: Run AI Loop
        id: ai_loop
        timeout-minutes: 360
        continue-on-error: true
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          FIREWORKS_AI_API_KEY: ${{ secrets.FIREWORKS_AI_API_KEY }}
          MAX_ATTEMPTS: ${{ env.MAX_ATTEMPTS }}
        run: |
          deno run --allow-all scripts/ai/main.ts
          echo "success=$?" >> "$GITHUB_OUTPUT"
          echo "last_attempt=$LAST_ATTEMPT" >> "$GITHUB_OUTPUT"

      - name: Upload attempts log
        uses: actions/upload-artifact@v4
        with:
          name: attempts-log
          path: attempts.txt

      - name: Create PR or Issue
        if: always() && ${{ github.event.inputs.pr-on-fail }}
        uses: peter-evans/create-pull-request@v5
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          token: ${{ env.GH_TOKEN }}
          commit-message: "AI Loop"
          title: "AI Loop for ${{ env.BRANCH }} (Attempts: ${{ steps.ai_loop.outputs.last_attempt }} / ${{ env.MAX_ATTEMPTS }})"
          body: |
            - Successfully fixed: ${{ steps.ai_loop.outputs.success == '0' && 'Yes' || 'No' }}
            - Total attempts: ${{ env.MAX_ATTEMPTS }}
            - Source branch: `${{ env.BRANCH }}`
            - Last attempt: ${{ steps.ai_loop.outputs.last_attempt }}
            - [View run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            - [View attempts log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.attempts-log.outputs.artifact_id }})
          branch: ${{ env.BRANCH }}-ai-loop-${{ github.run_id }}
          base: ${{ env.BRANCH }}
